### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by civvie17** [LocalInsomniac/NTMAi#1]
"Execution could not continue.

Script error, "ntmai.pk3:decaldef.txt line 31:
Unknown keyword 'OpaqueBlood'"

**Comment by ddoomguy** [comment]
Update to the latest version of GZDoom (nightly builds.)

**Comment by ddoomguy** [comment]
If you need more help, join our discord - https://discord.gg/2x4dW5y

**Comment by localins** [comment]
Update your GZDoom. OpaqueBlood is a new feature.

Also just join the Discord (the link ddoomguy sent) if you need any help with launch issues.
