### ISSUE TITLE
1.0-ALPHA-RC8 + AUGER;ZENITH 

### ISSUE THREAD

**Issue by m0rb** [LocalInsomniac/NTMAi#17]
got excited to check out AUGER;ZENITH support with the recent update

seems the shotgun has a really unique characteristic with the pwad; it continuously plays the peter and the wolf string section sample every time it's brought to an idle animation state

I'm running a somewhat more recent build of gzdoom
---
GZDoom g4.12pre-471-g682dd1b22-m - 2024-03-22 10:35:46 -0300 - SDL version
Compiled on Mar 27 2024

OS: Fedora Linux 39 (Workstation Edition), Linux 6.7.10-200.fc39.x86_64 on x86_64
GZDoom version g4.12pre-471-g682dd1b22-m

**Comment by localins** [comment]
Load NTMAi **after** AUGER;ZENITH. This also applies to all of the other WADs that this mod has special support for. You can use a launcher or command line of your preference to change the load order.

**Comment by m0rb** [comment]
Hey again

Got around to playing again and got to MAP21

Seems that the crushers are somehow blocking Romero's demise by the switched barrel explosions, with and without the Blood-style explosion modifier being set.

Tried increasing the radius and damage amounts, scaling, etc. No dice. 

Can noclip straight into the tower and shoot the barrels. Damage is dealt. Map ends.

idgi. I'm not intimately familiar with ACS / ZScript so maybe you have a better idea how to approach this one. 

Wish I had a solution.  :<

**Comment by localins** [comment]
Looks like Blood explosion damage doesn't play nice with MAP21. I've added a compatflag that disables it for that specific map in f93f76e. Other than that, everything else seems fine on my end.

**Comment by m0rb** [comment]
Apparently the savestate I was using for testing kept re-enabling the Blood explosion stuff. D'oh.

Confirmed the updates to dev branch did the trick. Thanks! :)
