### ISSUE TITLE
[Enhancement] SubMachine Gun

### ISSUE THREAD

**Issue by SkullGamer205** [LocalInsomniac/NTMAi#19]
- Add SMG (Which is from the Doom posters) (Preview Below)
![Like This](https://darmarit.org/searx/image_proxy?url=https%3A%2F%2Fi.pinimg.com%2Foriginals%2Fb0%2F02%2F4a%2Fb0024a953ac44c9dea34068f6b5cbd28.png&h=c933f526e5c334a7f9049b0810170302b9a76a5afa0e54439f945d5309fe3852)
![Like This 2](https://github.com/LocalInsomniac/NTMAi/assets/61167080/2945fc6c-4f16-406d-9185-32105cee8bb1)
1 Picture - Poster
2 Picture - Brutal Doom v22

**Comment by localins** [comment]
Nay.
