### ISSUE TITLE
Enemy Stuck in Line Portal

### ISSUE THREAD

**Issue by UnizoneDev** [LocalInsomniac/NTMAi#2]
Sometimes, when Enemies follow you around in custom maps, I've noticed that they sometimes get stuck in Line Portals, causing them to Flicker and Walk in Place.

Can you fix this, pretty please?

**Comment by localins** [comment]
Can you provide a sample map of where this issue occurs?

**Comment by UnizoneDev** [comment]
> Can you provide a sample map of where this issue occurs?

Sure, here you go!

http://www.mediafire.com/file/645aaunukp3w6xy/LINETEST.wad/file

**Comment by localins** [comment]
Upon closer inspection I have noticed that the enemy gets rarely stuck when going through the line portal, however when they pass through it, they start flickering for very few frames.

Keep in mind that the monster movement code is from Hideous Destructor, which means there might be some issues I don't understand how to fix.

There are other issues like monsters getting stuck on teleports (infinite teleport effect) and extreme twitching when "Interpolate monster movement" is disabled. I'll look into this more when I have the time.

**Comment by localins** [comment]
Appears to be fixed in 1.0-ALPHA-RC1 which is a full rewrite of the mod and offers different movement styles for monsters. I'll put this on hold for now.
